from PyQt5 import QtCore, QtGui, QtWidgets
import hashlib
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 570)
        self.hisobla = QtWidgets.QPushButton(Form)
        self.hisobla.setGeometry(QtCore.QRect(660, 80, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hisobla.setFont(font)
        self.hisobla.setObjectName("hisobla")
        self.hisobla.clicked.connect(self.heshhisoblash)
        self.malumot = QtWidgets.QLineEdit(Form)
        self.malumot.setGeometry(QtCore.QRect(20, 80, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.malumot.setFont(font)
        self.malumot.setObjectName("malumot")
        self.uningheshi = QtWidgets.QLineEdit(Form)
        self.uningheshi.setGeometry(QtCore.QRect(20, 310, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.uningheshi.setFont(font)
        self.uningheshi.setObjectName("uningheshi")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 40, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def heshhisoblash(self):
        matn=self.malumot.text()
        matnb=bytes(matn,'utf-8')
        md55=hashlib.md5(matnb)
        self.uningheshi.setText(md55.hexdigest())
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hisobla.setText(_translate("Form", "Hisobla"))
        self.label.setText(_translate("Form", "Ma\'lumot"))
        self.label_2.setText(_translate("Form", "Ma\'lumotning hesh qiymati"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
