
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(962, 720)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.Kalgen = QtWidgets.QPushButton(Form)
        self.Kalgen.setGeometry(QtCore.QRect(240, 20, 441, 91))
        self.Kalgen.setObjectName("Kalgen")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 130, 911, 531))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.privkey = QtWidgets.QLineEdit(self.widget)
        self.privkey.setObjectName("privkey")
        self.horizontalLayout.addWidget(self.privkey)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pubkey = QtWidgets.QLineEdit(self.widget)
        self.pubkey.setObjectName("pubkey")
        self.horizontalLayout_2.addWidget(self.pubkey)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.message = QtWidgets.QLineEdit(self.widget)
        self.message.setObjectName("message")
        self.horizontalLayout_3.addWidget(self.message)
        self.Shifrla = QtWidgets.QPushButton(self.widget)
        self.Shifrla.setObjectName("Shifrla")
        self.horizontalLayout_3.addWidget(self.Shifrla)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.encrytext = QtWidgets.QLineEdit(self.widget)
        self.encrytext.setObjectName("encrytext")
        self.horizontalLayout_4.addWidget(self.encrytext)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Kalgen.setText(_translate("Form", "Kalitlarni generatsiyalash"))
        self.label.setText(_translate("Form", "Kalit"))
        self.label_2.setText(_translate("Form", "Ochiq kalit"))
        self.label_3.setText(_translate("Form", "Ma\'lumot"))
        self.Shifrla.setText(_translate("Form", "Shifrlash"))
        self.label_4.setText(_translate("Form", "Shifrma\'lumot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
